= Fortinet-related scripts, tools, syntax highlighting files and such
:toc:

In this repo I collect scripts, automation stitches, various tools I find useful in my work with Fortinet products. 
Make sure to watch this repository to get notified on updates. Your stars on the repository as a sign that you found it useful are appreciated, thanks.

== Collection of Fortigate automation stitches
This collection is work in progress, and will always be. If you have an idea, or already implemented an automation 
stitch not in the collection, I will be glad to add it for the benefit of all of us - yuri@yurisk.info. Also, if you try some stitch from this repository and things do not work as expected - feel free to open an issue/PR with details. 

Disclaimer: I cannot possibly test contents of this repo on all Fortigate models and FortiOS versions, and cannot guarantee 
that it will work on your gear, nor can predict all possible outcomes, so test before using in production. All stitches were tested on FortiOS 7.0.x and 7.2.x, and should work as is on 7.4.x as well.

https://github.com/yuriskinfo/Fortinet-tools/tree/main/Fortigate-automation-stitches#collection-of-fortigate-automation-stitches[Collection of Automation Stitches]


== Collection of Fortianalyzer Handlers
Mostly based on the Automation stitches above, but not completely. Allows to scale when managing multiple Fortigates and configuring auto-stitches becomes not practical. Fortianalyzer can send notification/alerts as well as notify Fortigate to run pre-configured automation stitch on the Fortigate itself. 
As always - please test before using in production. 

https://github.com/yuriskinfo/Fortinet-tools/tree/main/Fortianalyzer-handlers[Fortianalyzer Handlers collection]

== Packet captures done on Fortinet equipment

Collection of .pcap packet captures done on Fortinet products (mostly on Fortigates, but not all). TO illustrate labs/experiments I write about in my blog and to have collection for all to use to learn about networking in general (BGP on Fortigate is the same BGP as on Cisco/Juniper/etc.) and Fortinet-specific products in particular. 


https://github.com/yuriskinfo/Fortinet-tools/tree/main/Wireshark-ready-packet-captures[Wireshark-ready packet captures]


== Custom Fortianalyzer Reports Collection

https://github.com/yuriskinfo/Fortinet-tools/tree/main/Fortianalyzer-custom-reports